= NetXMS Documentation UI
:experimental:

This is a custom UI for NetXMS documentation site. It is based on Antora default UI.

== Getting Started

 $ npm install

== Preview

 $ npx gulp preview

== Package for Use with Antora

 $ npx gulp bundle

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ npx gulp bundle:pack

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

=== Source Maps

The build consolidates all the CSS and client-side JavaScript into combined files, [.path]_site.css_ and [.path]_site.js_, respectively, in order to reduce the size of the bundle.
{url-source-maps}[Source maps] correlate these combined files with their original sources.

This "`source mapping`" is accomplished by generating additional map files that make this association.
These map files sit adjacent to the combined files in the build folder.
The mapping they provide allows the debugger to present the original source rather than the obfuscated file, an essential tool for debugging.

In preview mode, source maps are enabled automatically, so there's nothing you have to do to make use of them.
If you need to include source maps in the bundle, you can do so by setting the `SOURCEMAPS` environment variable to `true` when you run the bundle command:

 $ SOURCEMAPS=true npx gulp bundle

In this case, the bundle will include the source maps, which can be used for debugging your production site.

== Copyright and License

Antora default UI Copyright (C) 2017-present OpenDevise Inc. and the Antora Project.
NetXMS Documentation UI (C) 2025-present Raden Solutions, SIA.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by OpenDevise Inc.
