name: Build and Bundle UI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Bundle UI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Bundle
        run: npx gulp bundle

      - name: Move 'latest' Tag to Current Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f latest
          git push origin latest --force

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Snapshot
          draft: false
          prerelease: false
          files: build/ui-bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
